name: Debug Vercel Event

on:
  deployment_status:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Branch
        run: |
          echo "REF=${{ github.event.deployment.ref }}"
          echo "ENV=${{ github.event.deployment.environment }}"
          echo "URL=${{ github.event.deployment_status.environment_url }}"
